changed dumuxproject to make pardiso work
git-svn-id: svn://svn.iws.uni-stuttgart.de/DUMUX/dune-mux/trunk@156 2fb0f335-1f38-0410-981e-8018bf24f1b0

diff --git a/bin/dumuxproject b/bin/dumuxproject
--- a/bin/dumuxproject
+++ b/bin/dumuxproject
@@ -14,7 +14,19 @@ canonicalname(){
      echo Usage: canonicalname path > /dev/stderr
      return 1
   fi
-  readlink $1 || echo "$(dirname $1)/$(basename $1)"
+  name="$1"
+  while test -L "$name"; do
+    if ! test -e "$name"; then
+      echo $name: file not found > /dev/stderr
+      return 1
+    fi
+    if newname="`readlink $name`"; then
+      name="$newname"
+    else
+      echo "$(dirname $name)/$(basename $name)"
+    fi
+  done
+  echo $name
 }
 
 canonicalpath(){
@@ -23,6 +35,19 @@ canonicalpath(){
      return 1
   fi
   (cd $(dirname $(canonicalname $1)) && pwd)
+}
+
+pkg_config_dependencies(){
+    if test $# -ne 1; then
+	echo Usage: pkg_config_dependencies name > /dev/stderr
+	return 1
+    fi
+    name="$1"
+    depends="`pkg-config --variable=DEPENDENCIES $name| sed -e 's/,/ /g'`"
+    for pkg in $depends; do
+	depends="$depends `pkg_config_dependencies $pkg`"
+    done
+    echo $depends
 }
 
 modulesexist(){
@@ -107,15 +132,6 @@ if [ "$MODULES" = "" ]; then
   find_modules_in_path
 fi
 
-if [ "$MODULES" = "" ]; then
-  echo "ERROR">/dev/stderr
-  echo "No dune modules were found!">/dev/stderr
-  echo "Did you forget to specify the places where ">/dev/stderr
-  echo "you installed your modules in the ">/dev/stderr
-  echo "DUNE_CONTROL_PATH environment variable?" >/dev/stderr
-  exit 1;
-fi
-
 # get the real module names
 SRC_MODULES=""
 for i in $MODULES; do
@@ -128,6 +144,18 @@ PKG_MODULES="`pkg-config --list-all | grep dune | cut -d' ' -f1`"
 
 # merge lists
 ALL_MODULES="`echo $SRC_MODULES $PKG_MODULES | tr ' ' '\n' | sort | uniq`"
+
+
+if [ "$ALL_MODULES" = "" ]; then
+  echo "ERROR">/dev/stderr
+  echo "No dune modules were found!">/dev/stderr
+  echo "Did you forget to specify the places where ">/dev/stderr
+  echo "you installed your modules in the ">/dev/stderr
+  echo "DUNE_CONTROL_PATH environment variable">/dev/stderr
+  echo "and adjusted the PKG_CONFIG_PATH environment">/dev/stderr
+  echo "accordingly?" >/dev/stderr
+  exit 1;
+fi
 
 ################## READ OPTIONS ##################
 
@@ -207,6 +235,7 @@ C_DELIM
 ## Create the parameters passed to DUNE_CHECK_ALL
 
 # save module list of dunemodules.inc
+set -x
 save_MODULES=$MODULES
 for name in $DEPENDENCIES; do
   mod="`fix_variable_name $name`"
@@ -219,13 +248,14 @@ for name in $DEPENDENCIES; do
     MODULES=$save_MODULES
   else
     # found via pkg-config
-    M_DEPS="`pkg-config --variable=Requires $name`"
+    M_DEPS="`pkg_config_dependencies $name` $name"
+    #M_DEPS="`pkg-config --variable=Requires $name`"
   fi
   for dep in $M_DEPS; do
       CHECK="$CHECK [$dep]"
   done
 done
-
+set +x
 make_unique "$CHECK"
 
 # insert , between modules
@@ -246,17 +276,16 @@ cat > "$PROJECT/configure.ac" <<C_DELIM
 # -*- Autoconf -*-
 # Process this file with autoconf to produce a configure script.
 AC_PREREQ(2.50)
-AC_INIT(dune-mux, 0.1, bernd@iws.uni-stuttgart.de)
-AM_INIT_AUTOMAKE(dune-mux, 0.1, bernd@iws.uni-stuttgart.de)
-AC_CONFIG_SRCDIR([test/diffusion/test_diffusion.cc])
+DUNE_AC_INIT # gets module version from dune.module file
+AM_INIT_AUTOMAKE($PROJECT, $VERSION, $MAINTAINER)
+AC_CONFIG_SRCDIR([$CMODULE.cc])
 AM_CONFIG_HEADER([config.h])
-#AC_SUBST([LOCAL_LIBS], '$(top_srcdir)/lib/libdunemux.la')
-AC_SUBST([LOCAL_LIBS], '$(top_srcdir)/dumux/libdumux.la')
+
 
 # we need no more than the standard DE-stuff
-# this module depends on dune-common dune-disc dune-fem dune-grid dune-istl
-# this implies checking for [dune-common], [dune-istl], [dune-grid], [dune-disc]
-DUNE_CHECK_ALL([dune-common], [dune-istl], [dune-grid], [dune-disc])
+# this module depends on $DEPENDENCIES
+# this implies checking for $CHECK
+DUNE_CHECK_ALL($CHECK)
 
 AC_DEFUN([SET_PARDISO], [
 AC_PREREQ(2.50)
@@ -265,36 +294,36 @@ acx_pardiso_ok=no
 
 AC_ARG_WITH(pardiso,
 	[AC_HELP_STRING([--with-pardiso=<lib>], [use PARDISO library <lib>])])
-case $with_pardiso in
+case \$with_pardiso in
 	yes | "") ;;
 	no) acx_pardiso_ok=disable ;;
-	-* | */* | *.a | *.so | *.so.* | *.o) PARDISO_LIBS="$with_pardiso" ;;
-	*) PARDISO_LIBS="-l$with_pardiso" ;;
+	-* | */* | *.a | *.so | *.so.* | *.o) PARDISO_LIBS="\$with_pardiso" ;;
+	*) PARDISO_LIBS="-l\$with_pardiso" ;;
 esac
 
 # Get fortran linker names of PARDISO functions to check for.
 AC_F77_FUNC(pardisoinit)
 
-acx_pardiso_save_LIBS="$LIBS"
-LIBS="$BLAS_LIBS -llapack -lg2c $LIBS $FLIBS"
+acx_pardiso_save_LIBS="\$LIBS"
+LIBS="\$BLAS_LIBS -llapack -lg2c \$LIBS \$FLIBS"
 
 # First, check PARDISO_LIBS environment variable
-if test $acx_pardiso_ok = no; then
-if test "x$PARDISO_LIBS" != x; then
-	save_LIBS="$LIBS"; LIBS="$PARDISO_LIBS $LIBS"
-	AC_MSG_CHECKING([for $pardisoinit in $PARDISO_LIBS])
-	AC_TRY_LINK_FUNC($pardisoinit, [acx_pardiso_ok=yes], [PARDISO_LIBS=""])
-	AC_MSG_RESULT($acx_pardiso_ok)
-	LIBS="$save_LIBS"
+if test \$acx_pardiso_ok = no; then
+if test "x\$PARDISO_LIBS" != x; then
+	save_LIBS="\$LIBS"; LIBS="\$PARDISO_LIBS \$LIBS"
+	AC_MSG_CHECKING([for \$pardisoinit in \$PARDISO_LIBS])
+	AC_TRY_LINK_FUNC(\$pardisoinit, [acx_pardiso_ok=yes], [PARDISO_LIBS=""])
+	AC_MSG_RESULT(\$acx_pardiso_ok)
+	LIBS="\$save_LIBS"
 fi
 fi
 
 AC_SUBST(PARDISO_LIBS)
 
-LIBS="$acx_pardiso_save_LIBS"
+LIBS="\$acx_pardiso_save_LIBS"
 
 # Finally, execute ACTION-IF-FOUND/ACTION-IF-NOT-FOUND:
-if test x"$acx_pardiso_ok" = xyes; then
+if test x\$acx_pardiso_ok = xyes; then
         ifelse([$1],,AC_DEFINE(HAVE_PARDISO,1,[Define if you have a PARDISO library.]),[$1])
         :
 else
@@ -306,15 +335,15 @@ fi
 SET_PARDISO
 
 # implicitly set the Dune-flags everywhere
-AC_SUBST(AM_CPPFLAGS, $ALL_PKG_CPPFLAGS)
-AC_SUBST(AM_LDFLAGS, $ALL_PKG_LDFLAGS)
-LIBS="$DUNE_LIBS $ALL_PKG_LIBS $PARDISO_LIBS $BLAS_LIBS"
+AC_SUBST(AM_CPPFLAGS, \$ALL_PKG_CPPFLAGS)
+AC_SUBST(AM_LDFLAGS, \$ALL_PKG_LDFLAGS)
+LIBS="\$DUNE_LIBS \$ALL_PKG_LIBS \$PARDISO_LIBS \$BLAS_LIBS"
 
 AC_CONFIG_FILES([Makefile])
 AC_OUTPUT
 # finally print the summary information
 DUNE_SUMMARY_ALL
-echo "Pardiso..........: $acx_pardiso_ok"
+echo "Pardiso..........: \$acx_pardiso_ok"
 echo 
 C_DELIM
 
@@ -369,6 +398,7 @@ for OPT in "\$@"; do
             if test -d "\$OPT/share/dune-common/am"; then
               am_dir="\$OPT/share/dune-common/am"
             fi
+            PATH="\$PATH:\$OPT/bin"
             ;;
     esac
 done
